new Vue({
	el:'#app1',
	data:{
		pinzhiList:[
			{
				imgUrl:'images/vue_practice_1_1.jpg',
				imgHeader:'新品首发',
				imgTitle:'荣耀系列 今日特惠',
				className:'new_goods'
			},
			{
				imgUrl:'images/vue_practice_1_2.jpg',
				imgHeader:'会逛',
				imgTitle:'厨具超级品牌日199减100',
				className:'guang'
			},
			{
				imgUrl:'images/vue_practice_1_3.jpg',
				imgHeader:'奢侈打牌',
				imgTitle:'尽享品质生活',
				className:'she'
			},
			{
				imgUrl:'images/vue_practice_1_4.jpg',
				imgHeader:'智能生活',
				imgTitle:'智能潮货，嗨购不停',
				className:'zhineng'
			},
			{
				imgUrl:'images/vue_practice_1_5.jpg',
				imgHeader:'京东超市',
				imgTitle:'精选超值好货天天特价',
				className:'chaoshi'
			},
			{
				imgUrl:'images/vue_practice_1_6.jpg',
				imgHeader:'白条商城',
				imgTitle:'最高12期免息',
				className:'baitiao'
			},
		]
	}
})